### ISSUE TITLE
Feature Request : Add a CLI

### ISSUE THREAD

**Issue by cool-mist** [15Dkatz/official_joke_api#138]
- This could be useful as a terminal init script similar to [fortune + cowsay](https://en.wikipedia.org/wiki/Cowsay). 
- The cli can use one of the following as sources of jokes
   - embedded jokes.json as part of the build
   - official joke api
   - self hosted instance of joke api

**Grab a random joke!**

`$> joke`

**Grab ten random jokes!**

`$> joke -n 10`

**Grab jokes by type!**

`$> joke programming`
`$> joke programming -n 10`

**Grab joke by id!**

`$> joke <id>`

**Comment by seburbandev** [comment]
@cool-mist I recently wrote a cli app that utilises this joke API. It only supports random joke endpoint at the moment but I was considering adding flags to target other endpoints in the future. The cowsay looks fun. I might consider adding that too. You can always raise an issue and suggest a feature on my repo [chuckle-cli](https://github.com/seburbandev/chuckle-cli)

**Comment by cool-mist** [comment]
I've added a CLI for this at https://github.com/cool-mist/joke-cli/tree/main
