### ISSUE TITLE
API call limit

### ISSUE THREAD

**Issue by gustavofjordao021** [15Dkatz/official_joke_api#43]
Hi there!

We found your API and wanted to use it for our project at Ironhack Miami. However, we have one question: what is the API call limit? We wanted to know so we don't surpass it during testing and deployment.

Please let me know!

**Comment by yarodevuci** [comment]
@15Dkatz same question

**Comment by iamganeshagrawal** [comment]
Hy @gustavofjordao021 & @yarodevuci 

Here in this API @15Dkatz used his own rate-limiting middleware that allowed per **IP 100 requests per 15 minutes**.

Check Limiting-middleware [here](https://github.com/15Dkatz/limiting-middleware)

**Comment by skwebdeveloper** [comment]
Thanks @iamganeshagrawal
