### ISSUE TITLE
Feature Request: an endpoint that lists all of the types of jokes

### ISSUE THREAD

**Issue by chrispine** [15Dkatz/official_joke_api#60]
What a fun API! One thing I do wish it had, though is a way to query for the different types of jokes that can be used in the `jokes/:type/random` endpoint.

**Comment by Warhawk947** [comment]
that would be cool

**Comment by rhuangabrielsantos** [comment]
Hello, now just wait hahah :+1:

**Comment by 15Dkatz** [comment]
Thanks for the request! This has been added: https://github.com/15Dkatz/official_joke_api?tab=readme-ov-file#get-joke-types
