### ISSUE TITLE
Endpoint to retrieve specific joke(s)

### ISSUE THREAD

**Issue by nosmirck** [15Dkatz/official_joke_api#73]
Options:

One joke
jokes/{id}
jokes?id={id}

Multiple specific jokes
jokes?id={id1},{id2},{id3},...,{idn}
jokes?id={id1}..{idn}
jokes?id={id1}..{idn},{idn+1}

**Comment by Sainan** [comment]
This is already a thing ("Grab joke by id!"), although it is broken on the hosted appspot version.

**Comment by Sainan** [comment]
It now works on the hosted appspot version, so issue can be closed.
