### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by eklavyadev** [15Dkatz/official_joke_api#90]
The endpoint we use to fetch jokes is commonly https://official-joke-api.appspot.com/jokes/random which is not reachable right now and hanging up the servers

**Comment by dj-bauer** [comment]
I have the same issue

**Comment by Lerado** [comment]
Same here. Why is it doing that only when I need this amazing api ?? :(

**Comment by ralfz123** [comment]
🥺

**Comment by lianulloa** [comment]
Can some one please merge pr #91  @15Dkatz

**Comment by chuckreynolds** [comment]
Ditto. whole site shows 500 https://official-joke-api.appspot.com

**Comment by Makdash49** [comment]
Yes, I'm getting 500 also.

**Comment by danruiyot** [comment]
you can try this [one](https://twittezer.herokuapp.com/)

**Comment by WoosterInitiative** [comment]
> you can try this [one](https://twittezer.herokuapp.com/)

How is that one used? I'm trying to complete [Create a Windows Service using BackgroundService](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service) and that uses the "random" tag.

**Comment by danruiyot** [comment]
> > you can try this [one](https://twittezer.herokuapp.com/)
> 
> @danruiyot
> 
> How is that one used? I'm trying to complete [Create a Windows Service using BackgroundService](https://docs.microsoft.com/en-us/dotnet/core/extensions/windows-service) and that uses the "random" tag.

then [this](https://twittezer.herokuapp.com/random) will do

**Comment by marlonveiga-santos** [comment]
In the same week I was going to create a project that would consume this api it crashed. 
So I created this solution compatible with the original api and new features. Please try and let me know if it's useful or not:

[https://sharp-mestorf-1d7507.netlify.app/.netlify/functions/index/random_joke](https://sharp-mestorf-1d7507.netlify.app/.netlify/functions/index/random_joke)

Home: [https://sharp-mestorf-1d7507.netlify.app/.netlify/functions/index/api/](https://sharp-mestorf-1d7507.netlify.app/.netlify/functions/index/api/)

**Comment by eklavyadev** [comment]
All above APIs' are too helpful. But what about setting a new system in place? I think it would also help to merge new jokes as the authors not accepting PRs' for now. I have created https://karljoke.herokuapp.com
Hopefully this API will work same as this one
Contributions are welcome 🎉🎉

**Comment by ngotrongphuc** [comment]
> All above APIs' are too helpful. But what about setting a new system in place? I think it would also help to merge new jokes as the authors not accepting PRs' for now. I have created https://karljoke.herokuapp.com
> Hopefully this API will work same as this one
> Contributions are welcome 🎉🎉

Why do you use POST method to get jokes?

**Comment by eklavyadev** [comment]
> Why do you use POST method to get jokes?
I had to do it, for future it won't clash with other endpoints using GET requests and also post request seems good in APIs. I have no problem in changing it....would it be better?

**Comment by chuckreynolds** [comment]
> Home: https://nova-joke-api.netlify.app/.netlify/functions/index/api

I'll swap to this endpoint for now, but @marlonveiga-santos you plan to keep this running in perpetuity?

**Comment by marlonveiga-santos** [comment]
> > Home: https://nova-joke-api.netlify.app/.netlify/functions/index/api
> 
> I'll swap to this endpoint for now, but @marlonveiga-santos you plan to keep this running in perpetuity?

Yes !
At the moment I use Netlify's free plan which provides 125k requests per month. I believe it will not be necessary to change this plan anytime soon.

I also want to add more jokes and categories this month, but always keeping the original api's format.

**Comment by chuckreynolds** [comment]
> Yes ! At the moment I use Netlify's free plan which provides 125k requests per month. I believe it will not be necessary to change this plan anytime soon.
> 
> I also want to add more jokes and categories this month, but always keeping the original api's format.

Nice... i just use it for a chat bot ... few req a day so no big deal .but good to hear. cheers

**Comment by zaourzag** [comment]
Oh btw, I've also hosted the api on [here](https://jokes.zakariaa.nl)

**Comment by marlonveiga-santos** [comment]
> Oh btw, I've also hosted the api on [here](https://jokes.zakariaa.nl)

It's nice ! 

I think that with more options, more people will be able to use this api without fearing an outage.

**Comment by zaourzag** [comment]
> > Oh btw, I've also hosted the api on [here](https://jokes.zakariaa.nl)
> 
> It's nice !
> 
> I think that with more options, more people will be able to use this api without fearing an outage.

The reason I setup this api is because a bot I contribute to used the command i made with this api, ofc that didn't work anymore and i needed a quick solution. I'm using azure because I had put 2 and 2 together. I have a 100 euro azure scholarship and I'm otherwise wasting it. Around 10 euros a month of free money for this! This was my last resort cuz i actually send him a mail but he didn't respond :C

**Comment by 15Dkatz** [comment]
I fixed the API to get it running again. Try: https://official-joke-api.wl.r.appspot.com/

**Comment by eklavyadev** [comment]
@15Dkatz Finally you checked out after a year! That's gr8. Now make sure to check site status after accepting PRs' 😄
